name: Deployment Workflow Monodog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: "@mindfiredigital/monodog Build, Lint, and Test"
    runs-on: ubuntu-latest
    permissions:
        contents: write # Required to create release tags and update the changelog
        issues: write   # Required to close issues/PRs linked in the changelog
        pull-requests: write # Required for creating release pull requests (if configured)

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: "Install dependencies"
        run: pnpm install --ignore-scripts --no-frozen-lockfile

      - name: "Create build"
        run: pnpm run build

      - name: "Lint code"
        run: pnpm run lint

      - name: "Run tests"
        run: pnpm test

  create-github-release:
    name: Create GitHub release document and publish to npm
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
      packages: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack
        run: npm install -g pnpm

      - name: 'Install dependencies with pnpm'
        run: pnpm install --no-frozen-lockfile --ignore-scripts

      - name: 'Build application'
        run: pnpm turbo run build

      - name: 'Set Git user name and email'
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Generate Changeset from commit messages
        run: pnpm changeset:autogenerate

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1.4.1
        with:
          publish: npx changeset publish
        env:
          # GITHUB_TOKEN is used for GitHub releases/tags/comments
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN is used for publishing to the npm registry
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

